name: My first Worklfow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: Welcome message
        run: echo "My first Github Actions Job"

      - name: List Files
        run: ls -a

      - name: install_cowsay
        run: sudo apt install cowsay -y
          
      - name: create_file
        run: cowsay -f dragon "Hello" > file2.txt

      - name: show file
        run: cat file2.txt
